version: '3.8'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=music_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=34896GAZ
    networks:
      - nestjs-network

  server:
    build: server/
    env_file:
      - ./server/.env
    container_name: server
    ports:
      - '7000:7000'
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - nestjs-network

  client:
    build: client/
    container_name: client
    ports:
      - '4000:4000'
    depends_on:
      - server

volumes:
  data:

networks:
  nestjs-network:
    external: false
    name: nestjs-network
