version: '3.8'
services:
  postgres:
    image: postgres:14-bullseye
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: music_app
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data:/data/postgres
    networks:
      - nestjs-network

  # test:
  #   build: test/
  #   container_name: test
  #   ports:
  #     - '4001:4001'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - nestjs-network

  server:
    build: server/
    restart: always
    container_name: server
    ports:
      - '7000:7000'
    depends_on:
      - postgres
      # postgres:
      #   condition: service_healthy
    networks:
      - nestjs-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'sherlockstark00@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '34896GAZ'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    command: mkdir /var/lib/pgadmin/sessions
    volumes:
      - data:/var/lib/pgadmin
      - data:/var/lib/pgadmin/sessions
    ports:
      - '6050:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - nestjs-network

  client:
    build: client/
    container_name: client
    ports:
      - '4000:4000'
    depends_on:
      - server

volumes:
  data:

networks:
  nestjs-network:
    driver: bridge
