version: '3.8'
services:
  postgres:
    image: postgres:14-bullseye
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: music_app
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-network

  server:
    build: server/
    image: music_app-server:${TAG:-latest}
    restart: unless-stopper
    container_name: server
    ports:
      - '7000:7000'
    depends_on:
      - postgres
      # postgres:
      #   condition: service_healthy
    networks:
      - nestjs-network

  client:
    build: client/
    image: music_app-client:${TAG:-latest}
    restart: unless-stopper
    container_name: client
    ports:
      - '4000:4000'
    depends_on:
      - server

volumes:
  data:

networks:
  nestjs-network:
    driver: bridge
